baseURL = "http://www.akramz.space/"
languageCode = "en-us"
title = "Akram Zaytar"
theme = "hugo-notepadium"
copyright = "© 2020 Mohamed Akram Zaytar."
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "akramz"

# Google Analytics
googleAnalytics = "UA-155244480-1"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = ""  # if you have a logo png
slogan = "Ph.D. Student. Deep Learning, Climate Change, Low-Resource NLP."
license = ""  # CC License

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "mathjax"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "monokai"
darkTheme = "xcode-dark"  # apply this theme in dark mode
webFonts = true  # builtin: 'Source Code Pro'

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "local_deploy"
URL = "gs://www.akramz.space"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true