baseURL = "http://www.akramz.space/"
languageCode = "en-us"
title = "Akram Zaytar"
theme = "cactus"
copyright = "Akram Zaytar"
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "akramz"

# Google Analytics
googleAnalytics = "UA-155244480-1"

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4
    [markup.goldmark.renderer]
        unsafe = true  # enable raw HTML in Markdown

[params]
tagsOverview = false
colortheme = "white"
showProjectsList = true
projectsUrl = "https://github.com/akramz"
description = "I'm currently working at IBM Research as an applied scientist. I am interested in GeoSpatial data science, machine learning, and applied computer vision."
style = "light"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
logo = "https://i.imgur.com/978kCOa.png"  # if you have a logo png
slogan = "Ph.D. Student. Interested in Computer Science, Machine Learning, and Climate Change."
license = ""  # CC License
rss = true
mathjax = true

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = true  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "mathjax"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "monokai"
darkTheme = "xcode-dark"  # apply this theme in dark mode
webFonts = true  # builtin: 'Source Code Pro'

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

[deployment]
# By default, files are uploaded in an arbitrary order.
# Files that match the regular expressions in the "Order" list
# will be uploaded first, in the listed order.
order = [".jpg$", ".gif$"]

[[deployment.targets]]
# An arbitrary name for this target.
name = "local_deploy"
URL = "gs://www.akramz.space"

[[deployment.matchers]]
#  Cache static assets for 1 year.
pattern = "^.+\\.(js|css|svg|ttf)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[[params.social]]
name = "github"
link = "https://github.com/akramz"

[[params.social]]
name = "email"
link = "zaytarakram@gmail.com" # no need for "mailto:" at the start

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/akramz/"
